### ISSUE TITLE
kotlin extension, reverse mode, renderscript, replace core of jetifier?

### ISSUE THREAD

**Issue by mikehardy** [Fluicity/jetifire#1]
Hey man - a 10x speedup while going with what people definitely have for react-native dev (node) vs bash is fantastic

Some implementation things for jetifire:
- I think the kotlin file extension is .kt (rn-android-prompt package)
- it needs a reverse mode
- the renderscript package is an AndroidX migration that is undocumented but necessary (react-native-blur package shows it if I remember correctly)

All of those are pretty easy if you have the core working

(you can check these with the rn-androidx-demo repo I use for testing) - https://github.com/mikehardy/rn-androidx-demo

As people posted issues I added a package that showed them into that demo to make sure it passed, so it's as complete a test suite as I can make

If this implementation gets those things, would you be willing to merge in to the current jetifier bash version to replace the translation engine?

Then once it's stable I'll get the react-native-community guys to take it under their umbrella so it gets good maintenance

What do you think?

**Comment by m4tt72** [comment]
Hello @mikehardy, I took a look at what you mentioned and I added/fixed the following: 

✅ - fixed kotlin extention from `.kotlin` to `.kt`
✅ - added reverse mode
✅ - renderscript was already supported but needed to be fixed, check `lib/androidx-class-mapping.csv:1937`

I ran `jetifire` in the rn-androidx-demo repo you use for testing and the build was successful 🎉

As for merging into the current jetifier bash version to replace the translation engine, I might have to look into some stuff before taking the decision to do so. I'll get back to you asap!

**Comment by m4tt72** [comment]
Hey @mikehardy, I'll create a PR soon to merge with `jetifier`!

**Comment by mikehardy** [comment]
@m4tt72 that’s exciting! I wish the javascript version had existed 2 days earlier so I could have skipped bash entirely - in a javascript ecosystem using bash is pretty silly. Once it’s in I’ll grant the appropriate github + npm auths as well so there’s more than one of us able to do things, I think this is going to be critical infrastructure once RN0.60 (based on AndroidX) is out
